env:
  es2021: true
  node: true

plugins:
  - jest
  - import

extends:
  - airbnb-base
  - plugin:jest/recommended
  - plugin:import/recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/extensions: [2, 'ignorePackages', { 'js': 'always' }]
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
